### ISSUE TITLE
`node-sass` is deprecated

### ISSUE THREAD

**Issue by dotZak** [jayfreestone/hey#2]
Projects using hey.js break builds when running `npm` because `node-sass` is deprecated in favor of `sass`. Replacing `node-sass` can fix the issue, but really the dependency shouldn't be exposed down the line—`sass` should be a dev dependency instead of production.

**Comment by jayfreestone** [comment]
👋 Hey (pun intended)!

Appreciate the pull/issue.

Unfortunately this repo is unmaintained (4-5 years is a long time in the world of frontend 😅) and there's likely a bunch of work required in order to bring it back up-to-date — switching over to Dart Sass is only the tip of the iceberg. It's not a can of worms I'm dying to open.

The README probably ought to have `DEPRECATED` in the title etc, but I appreciate you're probably taking over development on the Portal (or similar?) and have inherited it as a dependency.

Forking it as you've done and making changes from there is probably the best approach.
